Adding correct client_id and access_key
There is a issue with the client_id send it to google.

Error: invalid_request

Missing required parameter: client_id